"""
Resource Consumption Tests

Validates that weapons correctly consume and respect resource limits:
- Energy consumption per beam shot
- Ammo consumption per projectile/seeker shot
- Weapons stop firing when resources depleted

These tests use small storage components (25 energy, 10 ammo) to verify
depletion behavior without requiring many shots.
"""
import pytest
import os
import json

import pygame

from game.simulation.entities.ship import Ship
from game.simulation.systems.battle_engine import BattleEngine


def create_ship_with_components(component_ids: list, name: str = "Test Ship") -> dict:
    """Create a minimal ship dict with specified components."""
    return {
        "name": name,
        "color": [255, 0, 0],
        "team_id": 1,
        "ship_class": "TestS_2L",
        "theme_id": "Federation",
        "ai_strategy": "test_do_nothing",
        "layers": {
            "CORE": [{"id": cid} for cid in component_ids],
            "ARMOR": []
        }
    }


@pytest.mark.simulation
class TestBeamResourceConsumption:
    """Test beam weapon energy consumption."""
    
    @pytest.fixture(autouse=True)
    def setup(self, isolated_registry, ships_dir):
        """Use isolated registry and store ships_dir."""
        self.ships_dir = ships_dir
    
    def _load_target(self) -> Ship:
        """Load stationary target for testing."""
        path = os.path.join(self.ships_dir, 'Test_Target_Stationary.json')
        with open(path, 'r') as f:
            data = json.load(f)
        ship = Ship.from_dict(data)
        ship.recalculate_stats()
        return ship
    
    def _create_attacker_with_limited_energy(self, generator: bool = True) -> Ship:
        """Create beam attacker with small energy storage (25 units).
        
        Beam consumes 10 energy per shot, so 2 shots max.
        """
        components = ["test_beam_med_acc", "test_storage_energy_small"]
        if generator:
            components.append("test_gen_fusion")
        ship_data = create_ship_with_components(components, "Limited Energy Attacker")
        ship = Ship.from_dict(ship_data)
        ship.recalculate_stats()
        # Start with small amount of energy
        ship.resources.set_value('energy', 25.0)
        return ship
    
    def test_RESOURCE_001_beam_consumes_energy(self):
        """
        RESOURCE-001: Beam weapon consumes energy per shot.
        
        Beam with 10 energy cost should deplete 25 energy small battery
        after 2 shots.
        """
        attacker = self._create_attacker_with_limited_energy(generator=True)
        target = self._load_target()
        
        initial_energy = attacker.resources.get_value('energy')
        
        # Position ships
        attacker.position = pygame.math.Vector2(0, 0)
        attacker.angle = 0
        target.position = pygame.math.Vector2(100, 0)
        target.angle = 0
        
        engine = BattleEngine()
        engine.start([attacker], [target], seed=42)
        attacker.current_target = target
        
        # Run a few ticks to fire some shots
        for _ in range(50):
            attacker.comp_trigger_pulled = True
            engine.update()
        
        engine.shutdown()
        
        # Energy should have been consumed (or regenerated by generator)
        # With generator, energy may replenish, but shots should have been fired
        assert target.hp < target.max_hp, \
            "Beam should have fired and dealt damage"
    
    def test_RESOURCE_002_beam_stops_when_depleted(self):
        """
        RESOURCE-002: Beam stops firing when energy depleted (no generator).
        
        With 25 energy and 10 per shot, weapon stops after 2 shots.
        """
        attacker = self._create_attacker_with_limited_energy(generator=False)
        target = self._load_target()
        
        # Position ships
        attacker.position = pygame.math.Vector2(0, 0)
        attacker.angle = 0  
        target.position = pygame.math.Vector2(100, 0)
        target.angle = 0
        
        engine = BattleEngine()
        engine.start([attacker], [target], seed=42)
        attacker.current_target = target
        
        # Run simulation until energy depleted
        for _ in range(100):
            attacker.comp_trigger_pulled = True
            engine.update()
        
        final_energy = attacker.resources.get_value('energy')
        engine.shutdown()
        
        # Energy should be depleted (less than cost of one shot)
        assert final_energy < 10, \
            f"Energy should be depleted, got {final_energy}"


@pytest.mark.simulation
class TestProjectileResourceConsumption:
    """Test projectile weapon ammo consumption."""
    
    @pytest.fixture(autouse=True)
    def setup(self, isolated_registry, ships_dir):
        """Use isolated registry and store ships_dir."""
        self.ships_dir = ships_dir
    
    def _load_target(self) -> Ship:
        """Load stationary target for testing."""
        path = os.path.join(self.ships_dir, 'Test_Target_Stationary.json')
        with open(path, 'r') as f:
            data = json.load(f)
        ship = Ship.from_dict(data)
        ship.recalculate_stats()
        return ship
    
    def _create_attacker_with_limited_ammo(self) -> Ship:
        """Create projectile attacker with small ammo storage (10 units).
        
        test_weapon_proj_fixed consumes 1 ammo per shot, so 10 shots max.
        """
        components = ["test_weapon_proj_fixed", "test_storage_ammo_small"]
        ship_data = create_ship_with_components(components, "Limited Ammo Projectile Attacker")
        ship = Ship.from_dict(ship_data)
        ship.recalculate_stats()
        ship.resources.set_value('ammo', 10.0)
        return ship
    
    def test_RESOURCE_003_projectile_consumes_ammo(self):
        """
        RESOURCE-003: Projectile weapon consumes ammo per shot.
        """
        attacker = self._create_attacker_with_limited_ammo()
        target = self._load_target()
        
        initial_ammo = attacker.resources.get_value('ammo')
        
        # Position ships
        attacker.position = pygame.math.Vector2(0, 0)
        attacker.angle = 0
        target.position = pygame.math.Vector2(100, 0)
        target.angle = 0
        
        engine = BattleEngine()
        engine.start([attacker], [target], seed=42)
        attacker.current_target = target
        
        # Run simulation
        for _ in range(200):
            if not target.is_alive:
                break
            attacker.comp_trigger_pulled = True
            engine.update()
        
        final_ammo = attacker.resources.get_value('ammo')
        engine.shutdown()
        
        # Ammo should have been consumed
        assert final_ammo < initial_ammo, \
            f"Ammo should be consumed: started {initial_ammo}, ended {final_ammo}"
    
    def test_RESOURCE_004_projectile_stops_when_depleted(self):
        """
        RESOURCE-004: Projectile weapon stops firing when ammo depleted.
        """
        attacker = self._create_attacker_with_limited_ammo()
        target = self._load_target()
        
        # Position ships
        attacker.position = pygame.math.Vector2(0, 0)
        attacker.angle = 0
        target.position = pygame.math.Vector2(100, 0)
        target.angle = 0
        
        engine = BattleEngine()
        engine.start([attacker], [target], seed=42)
        attacker.current_target = target
        
        # Run until ammo depleted (10 shots at 1-second reload = 10 seconds = 1000+ ticks)
        for _ in range(1200):
            attacker.comp_trigger_pulled = True
            engine.update()
        
        final_ammo = attacker.resources.get_value('ammo')
        engine.shutdown()
        
        # Ammo should be depleted
        assert final_ammo == 0, \
            f"Ammo should be fully depleted, got {final_ammo}"


@pytest.mark.simulation
class TestSeekerResourceConsumption:
    """Test seeker weapon ammo consumption."""
    
    @pytest.fixture(autouse=True)
    def setup(self, isolated_registry, ships_dir):
        """Use isolated registry and store ships_dir."""
        self.ships_dir = ships_dir
    
    def _load_target(self) -> Ship:
        """Load stationary target for testing."""
        path = os.path.join(self.ships_dir, 'Test_Target_Stationary.json')
        with open(path, 'r') as f:
            data = json.load(f)
        ship = Ship.from_dict(data)
        ship.recalculate_stats()
        return ship
    
    def _create_attacker_with_limited_ammo(self) -> Ship:
        """Create seeker attacker with small ammo storage (10 units).
        
        test_weapon_missile_omni consumes 5 ammo per shot, so 2 shots max.
        """
        components = ["test_weapon_missile_omni", "test_storage_ammo_small"]
        ship_data = create_ship_with_components(components, "Limited Ammo Seeker Attacker")
        ship = Ship.from_dict(ship_data)
        ship.recalculate_stats()
        ship.resources.set_value('ammo', 10.0)
        return ship
    
    def test_RESOURCE_005_seeker_consumes_ammo(self):
        """
        RESOURCE-005: Seeker weapon consumes ammo per launch.
        
        Seeker consumes 5 ammo per shot, so 10 ammo = 2 launches.
        """
        attacker = self._create_attacker_with_limited_ammo()
        target = self._load_target()
        
        initial_ammo = attacker.resources.get_value('ammo')
        
        # Position ships
        attacker.position = pygame.math.Vector2(0, 0)
        attacker.angle = 0
        target.position = pygame.math.Vector2(500, 0)
        target.angle = 0
        
        engine = BattleEngine()
        engine.start([attacker], [target], seed=42)
        attacker.current_target = target
        
        # Run simulation (seeker has 5s reload)
        for _ in range(600):
            if not target.is_alive:
                break
            attacker.comp_trigger_pulled = True
            engine.update()
        
        final_ammo = attacker.resources.get_value('ammo')
        engine.shutdown()
        
        # Ammo should have been consumed
        assert final_ammo < initial_ammo, \
            f"Ammo should be consumed: started {initial_ammo}, ended {final_ammo}"
    
    def test_RESOURCE_006_seeker_stops_when_depleted(self):
        """
        RESOURCE-006: Seeker weapon stops launching when ammo depleted.
        """
        attacker = self._create_attacker_with_limited_ammo()
        target = self._load_target()
        
        # Position ships
        attacker.position = pygame.math.Vector2(0, 0)
        attacker.angle = 0
        target.position = pygame.math.Vector2(500, 0)
        target.angle = 0
        
        engine = BattleEngine()
        engine.start([attacker], [target], seed=42)
        attacker.current_target = target
        
        # Run until ammo depleted (allow for reload times)
        for _ in range(1200):
            attacker.comp_trigger_pulled = True
            engine.update()
        
        final_ammo = attacker.resources.get_value('ammo')
        engine.shutdown()
        
        # Ammo should be depleted
        assert final_ammo == 0, \
            f"Ammo should be fully depleted, got {final_ammo}"


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
