[pytest]
testpaths = tests
addopts = -n 1 --ignore=Tools --ignore=Refactoring --ignore-glob=*.txt --ignore=simulation_tests --junitxml=./.pytest_cache/test-results.xml
python_files = test_*.py
pythonpath = . Tools
norecursedirs = .* build dist CVS _darcs {arch} *.egg venv env .venv data ShipThemes Assets simulation_tests
markers =
    use_custom_data: marks tests that use custom test data and should skip production hydration
    simulation: marks tests as simulation tests
    slow: marks tests as slow running
