#!/usr/bin/env python3
"""
Approve or reject prospective projects generated by the sweep pipeline.

Approved projects are created in the project system via review_to_project.py.
Rejected projects are moved to the rejected_projects/ directory.

Usage:
    python approve_prospective_projects.py <review_folder> --approve all
    python approve_prospective_projects.py <review_folder> --approve "architecture,legacy"
    python approve_prospective_projects.py <review_folder> --reject "consistency"
    python approve_prospective_projects.py <review_folder> --list

Examples:
    python approve_prospective_projects.py 2026-02-10_sweep_full-codebase-sweep --list
    python approve_prospective_projects.py 2026-02-10_sweep_full-codebase-sweep --approve all
    python approve_prospective_projects.py 2026-02-10_sweep_full-codebase-sweep --approve "arch,legacy"
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Add parent to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from utils.config import RESULTS_DIR


def discover_proposals(prospective_dir: Path) -> list:
    """Discover all prospective project proposals in the directory.

    Returns a list of dicts with slug, title, finding_count, etc.
    """
    proposals = []

    if not prospective_dir.exists():
        return proposals

    for subdir in sorted(prospective_dir.iterdir()):
        if not subdir.is_dir():
            continue

        proposal_file = subdir / "proposal.md"
        findings_file = subdir / "findings.json"

        if not proposal_file.exists() or not findings_file.exists():
            continue

        # Parse proposal.md for title
        proposal_content = proposal_file.read_text(encoding='utf-8')
        title_match = re.search(
            r'^#\s+Prospective Project:\s*(.+)$',
            proposal_content,
            re.MULTILINE,
        )
        title = title_match.group(1).strip() if title_match else subdir.name

        # Parse findings.json for count and severity breakdown
        try:
            findings = json.loads(
                findings_file.read_text(encoding='utf-8')
            )
        except (json.JSONDecodeError, OSError):
            findings = []

        severity_counts = {}
        effort_counts = {}
        for f in findings:
            sev = f.get('severity', 'Unknown')
            severity_counts[sev] = severity_counts.get(sev, 0) + 1
            eff = f.get('effort', 'Unknown')
            effort_counts[eff] = effort_counts.get(eff, 0) + 1

        proposals.append({
            'slug': subdir.name,
            'title': title,
            'dir': subdir,
            'findings': findings,
            'finding_count': len(findings),
            'severity_counts': severity_counts,
            'effort_counts': effort_counts,
        })

    return proposals


def list_proposals(prospective_dir: Path) -> None:
    """List all available prospective project proposals."""
    proposals = discover_proposals(prospective_dir)

    if not proposals:
        print("No prospective project proposals found.")
        return

    print(f"\nFound {len(proposals)} prospective project(s):\n")
    print(
        f"{'#':<4} {'Slug':<35} {'Title':<40} "
        f"{'Findings':>8} {'Crit':>5} {'Maj':>5} {'Min':>5}"
    )
    print('-' * 110)

    for i, p in enumerate(proposals, 1):
        sc = p['severity_counts']
        print(
            f"{i:<4} {p['slug']:<35} {p['title'][:40]:<40} "
            f"{p['finding_count']:>8} "
            f"{sc.get('Critical', 0):>5} "
            f"{sc.get('Major', 0):>5} "
            f"{sc.get('Minor', 0):>5}"
        )

    print(f"\nUse --approve to create projects or --reject to archive.")


def match_proposals(
    proposals: list,
    selection: str,
) -> tuple:
    """Match user selection to proposals.

    Returns tuple of (matched, unmatched_slugs).
    Selection can be "all" or comma-separated slugs/partial slugs.
    """
    if selection.lower().strip() == 'all':
        return proposals, []

    slugs = [s.strip().lower() for s in selection.split(',')]
    matched = []
    unmatched = []

    for slug in slugs:
        found = False
        for p in proposals:
            if slug == p['slug'].lower() or slug in p['slug'].lower():
                if p not in matched:
                    matched.append(p)
                found = True
                break
        if not found:
            unmatched.append(slug)

    return matched, unmatched


def create_project_from_proposal(
    review_folder: Path,
    proposal: dict,
    phase_by: str = 'shard',
) -> str | None:
    """Create a real project from a prospective proposal.

    Returns the PROJ-XX ID if successful, None otherwise.
    """
    findings = proposal['findings']
    if not findings:
        print(f"  [SKIP] {proposal['slug']}: No findings")
        return None

    # Build comma-separated finding IDs
    finding_ids = ','.join(f['id'] for f in findings)
    title = proposal['title']

    # Build command
    script = Path(__file__).parent / "review_to_project.py"
    cmd = [
        sys.executable,
        str(script),
        str(review_folder),
        '--findings', finding_ids,
        '--title', title,
        '--phase-by', phase_by,
    ]

    print(f"  Creating project: {title}")
    print(f"    Findings: {len(findings)}")

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60,
            encoding='utf-8',
        )

        if result.returncode != 0:
            print(f"    [ERROR] Project creation failed:")
            # Show last few lines of stderr or stdout
            output = result.stderr or result.stdout
            for line in output.strip().split('\n')[-5:]:
                print(f"      {line}")
            return None

        # Extract PROJ-XX from output
        proj_match = re.search(r'(PROJ-\d+)', result.stdout)
        if proj_match:
            project_id = proj_match.group(1)
            print(f"    [OK] Created {project_id}")
            return project_id
        else:
            print(f"    [WARN] Project created but could not extract ID")
            return "PROJ-???"

    except subprocess.TimeoutExpired:
        print(f"    [ERROR] Project creation timed out")
        return None
    except Exception as e:
        print(f"    [ERROR] {e}")
        return None


def approve_projects(
    review_folder: Path,
    prospective_dir: Path,
    rejected_dir: Path,
    selection: str,
    phase_by: str = 'shard',
) -> dict:
    """Approve selected prospective projects and create real projects.

    Returns a summary dict with results.
    """
    proposals = discover_proposals(prospective_dir)

    if not proposals:
        print("ERROR: No prospective project proposals found.")
        return {'created': [], 'failed': [], 'rejected': []}

    matched, unmatched = match_proposals(proposals, selection)

    if unmatched:
        print(f"\n[WARN] Could not match these selections: {unmatched}")
        print("Available slugs:")
        for p in proposals:
            print(f"  - {p['slug']}")

    if not matched:
        print("\nERROR: No proposals matched the selection.")
        return {'created': [], 'failed': [], 'rejected': []}

    # Determine rejected proposals (everything not matched)
    rejected = [p for p in proposals if p not in matched]

    print(f"\n{'=' * 50}")
    print(f"Approving {len(matched)} project(s), "
          f"rejecting {len(rejected)}")
    print('=' * 50)

    # Create approved projects
    created = []
    failed = []

    for p in matched:
        project_id = create_project_from_proposal(
            review_folder, p, phase_by
        )
        if project_id:
            created.append({
                'slug': p['slug'],
                'title': p['title'],
                'project_id': project_id,
                'finding_count': p['finding_count'],
            })
        else:
            failed.append({
                'slug': p['slug'],
                'title': p['title'],
                'finding_count': p['finding_count'],
            })

    # Move rejected proposals
    rejected_results = []
    if rejected:
        rejected_dir.mkdir(parents=True, exist_ok=True)
        for p in rejected:
            src = p['dir']
            dst = rejected_dir / p['slug']
            try:
                if dst.exists():
                    shutil.rmtree(dst)
                shutil.move(str(src), str(dst))
                rejected_results.append({
                    'slug': p['slug'],
                    'title': p['title'],
                    'finding_count': p['finding_count'],
                })
                print(f"  [REJECTED] {p['slug']} -> rejected_projects/")
            except Exception as e:
                print(f"  [WARN] Could not move {p['slug']}: {e}")

    # Write approval log
    write_approval_log(
        prospective_dir, created, failed, rejected_results
    )

    return {
        'created': created,
        'failed': failed,
        'rejected': rejected_results,
    }


def reject_projects(
    prospective_dir: Path,
    rejected_dir: Path,
    selection: str,
) -> dict:
    """Reject selected prospective projects (move to rejected_projects/).

    Returns a summary dict.
    """
    proposals = discover_proposals(prospective_dir)

    if not proposals:
        print("ERROR: No prospective project proposals found.")
        return {'rejected': []}

    matched, unmatched = match_proposals(proposals, selection)

    if unmatched:
        print(f"\n[WARN] Could not match: {unmatched}")

    if not matched:
        print("\nERROR: No proposals matched the selection.")
        return {'rejected': []}

    rejected_dir.mkdir(parents=True, exist_ok=True)
    rejected_results = []

    for p in matched:
        src = p['dir']
        dst = rejected_dir / p['slug']
        try:
            if dst.exists():
                shutil.rmtree(dst)
            shutil.move(str(src), str(dst))
            rejected_results.append({
                'slug': p['slug'],
                'title': p['title'],
                'finding_count': p['finding_count'],
            })
            print(f"  [REJECTED] {p['slug']} -> rejected_projects/")
        except Exception as e:
            print(f"  [WARN] Could not move {p['slug']}: {e}")

    return {'rejected': rejected_results}


def write_approval_log(
    prospective_dir: Path,
    created: list,
    failed: list,
    rejected: list,
) -> None:
    """Write the approval log to prospective_projects/approval_log.md."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# Prospective Projects Approval Log",
        "",
        f"**Date:** {now}",
        "",
    ]

    if created:
        lines.append("## Approved and Created")
        lines.append("")
        lines.append("| Proposal | Project ID | Title | Findings |")
        lines.append("|----------|-----------|-------|----------|")
        for c in created:
            lines.append(
                f"| {c['slug']} | {c['project_id']} "
                f"| {c['title']} | {c['finding_count']} |"
            )
        lines.append("")

    if failed:
        lines.append("## Failed to Create")
        lines.append("")
        lines.append("| Proposal | Title | Findings | Reason |")
        lines.append("|----------|-------|----------|--------|")
        for f in failed:
            lines.append(
                f"| {f['slug']} | {f['title']} "
                f"| {f['finding_count']} | Creation error |"
            )
        lines.append("")

    if rejected:
        lines.append("## Rejected")
        lines.append("")
        lines.append("| Proposal | Title | Findings |")
        lines.append("|----------|-------|----------|")
        for r in rejected:
            lines.append(
                f"| {r['slug']} | {r['title']} | {r['finding_count']} |"
            )
        lines.append("")

    total_findings = (
        sum(c['finding_count'] for c in created)
        + sum(f['finding_count'] for f in failed)
        + sum(r['finding_count'] for r in rejected)
    )
    created_findings = sum(c['finding_count'] for c in created)

    lines.append("## Summary")
    lines.append(f"- Projects created: {len(created)}")
    lines.append(f"- Projects failed: {len(failed)}")
    lines.append(f"- Projects rejected: {len(rejected)}")
    lines.append(
        f"- Findings covered by created projects: "
        f"{created_findings}/{total_findings}"
    )
    lines.append("")
    lines.append(f"*Generated: {now}*")

    log_file = prospective_dir / "approval_log.md"
    log_file.write_text('\n'.join(lines), encoding='utf-8')
    print(f"\n  Approval log: {log_file}")


def print_summary(results: dict) -> None:
    """Print a final summary of the approval process."""
    created = results.get('created', [])
    failed = results.get('failed', [])
    rejected = results.get('rejected', [])

    print(f"\n{'=' * 50}")
    print("APPROVAL COMPLETE")
    print('=' * 50)

    if created:
        print(f"\nCreated {len(created)} project(s):")
        for c in created:
            print(
                f"  {c['project_id']}: {c['title']} "
                f"({c['finding_count']} findings)"
            )

    if failed:
        print(f"\nFailed to create {len(failed)} project(s):")
        for f in failed:
            print(f"  {f['slug']}: {f['title']}")

    if rejected:
        print(f"\nRejected {len(rejected)} project(s):")
        for r in rejected:
            print(f"  {r['slug']}: {r['title']}")

    if created:
        print(
            f"\nNext steps: Use 'Continue Project' prompt with any of "
            f"the created project IDs."
        )


def main():
    parser = argparse.ArgumentParser(
        description='Approve or reject prospective projects from a sweep',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # List available proposals
    python approve_prospective_projects.py 2026-02-10_sweep --list

    # Approve all proposals
    python approve_prospective_projects.py 2026-02-10_sweep --approve all

    # Approve specific proposals (partial slug matching)
    python approve_prospective_projects.py 2026-02-10_sweep --approve "arch,legacy"

    # Reject specific proposals
    python approve_prospective_projects.py 2026-02-10_sweep --reject "consistency"
        """
    )
    parser.add_argument(
        'review_folder',
        help='Review folder name or path',
    )
    parser.add_argument(
        '--approve', '-a',
        help=(
            'Approve proposals: "all" or comma-separated '
            'slugs/partial slugs'
        ),
    )
    parser.add_argument(
        '--reject', '-r',
        help='Reject proposals: comma-separated slugs/partial slugs',
    )
    parser.add_argument(
        '--list', '-l',
        action='store_true',
        help='List available proposals without taking action',
    )
    parser.add_argument(
        '--phase-by',
        choices=['severity', 'shard'],
        default='shard',
        help=(
            'How to organize phases in created projects '
            '(default: shard)'
        ),
    )

    args = parser.parse_args()

    # Resolve folder path
    folder_path = Path(args.review_folder)
    if not folder_path.is_absolute():
        if (RESULTS_DIR / args.review_folder).exists():
            folder_path = RESULTS_DIR / args.review_folder
        elif not folder_path.exists():
            print(f"ERROR: Review folder not found: {args.review_folder}")
            sys.exit(1)

    prospective_dir = folder_path / "prospective_projects"
    rejected_dir = folder_path / "rejected_projects"

    if not prospective_dir.exists():
        print(
            f"ERROR: No prospective_projects directory found in "
            f"{folder_path}"
        )
        print("Run generate_prospective_projects.py first.")
        sys.exit(1)

    # List mode
    if args.list:
        list_proposals(prospective_dir)
        sys.exit(0)

    # Must have either --approve or --reject
    if not args.approve and not args.reject:
        print("ERROR: Specify --approve, --reject, or --list")
        parser.print_help()
        sys.exit(1)

    # Handle approvals
    if args.approve:
        results = approve_projects(
            folder_path,
            prospective_dir,
            rejected_dir,
            args.approve,
            args.phase_by,
        )
        print_summary(results)

    # Handle rejections
    if args.reject:
        results = reject_projects(
            prospective_dir,
            rejected_dir,
            args.reject,
        )
        print_summary(results)


if __name__ == '__main__':
    main()
