import json
import os
import sys
from typing import Dict, List

# Placeholder for your actual LLM API Client (e.g., OpenAI, Anthropic, Gemini)
def call_llm(system_prompt: str, user_prompt: str) -> str:
    """
    Simulates an LLM call. Replace this with actual API integration.
    """
    print(f"--- Launching Agent ---")
    print(f"System: {system_prompt[:50]}...")
    print(f"User: {user_prompt[:50]}...")
    return f"Report generated by agent. [Mock Output for {system_prompt[:20]}]"

def load_file_context(base_path: str, files: List[str]) -> str:
    context = ""
    for file_path in files:
        full_path = os.path.join(base_path, file_path)
        if os.path.exists(full_path):
            with open(full_path, 'r', encoding='utf-8') as f:
                context += f"\n--- START FILE: {file_path} ---\n"
                context += f.read()
                context += f"\n--- END FILE: {file_path} ---\n"
        else:
            context += f"\n[WARNING: File not found: {file_path}]\n"
    return context

def spin_swarm(manifest_path: str):
    with open(manifest_path, 'r') as f:
        manifest = json.load(f)

    context_root = manifest.get("context_root", "./")
    output_dir = os.path.join(os.path.dirname(manifest_path), "reports")
    os.makedirs(output_dir, exist_ok=True)

    for agent in manifest["agents"]:
        role = agent["role"]
        focus = agent["focus"]
        files = agent.get("primary_files", [])
        
        print(f"Spinning up {role} on focus: {focus}")
        
        # 1. Build Context
        file_content = load_file_context(context_root, files)
        
        # 2. Construct Prompt
        system_prompt = f"You are a Specialist Reviewer focused on: {role}.\nYour specific focus is: {focus}."
        user_prompt = f"Analyze the following code context for issues related to your focus.\n\nContext:\n{file_content}"
        
        # 3. Execute
        report_content = call_llm(system_prompt, user_prompt)
        
        # 4. Save Report
        report_path = os.path.join(output_dir, f"{role}_Report.md")
        with open(report_path, 'w') as f:
            f.write(report_content)
        print(f"Report saved to {report_path}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python spin_swarm.py <path_to_swarm_manifest.json>")
    else:
        spin_swarm(sys.argv[1])
