#!/usr/bin/env python3
"""
Build continuous_loop/cycle_plan.md from newly-created projects.

Reads the most recent approval_log.md (or accepts --projects on CLI)
to discover which PROJ-XX entries were created by the sweep. Then reads
each project's plan.md for metadata and generates a cycle_plan.md in
the format expected by check_completion.py.

Usage:
    # Auto-detect from most recent approval log
    python continuous_loop/populate_cycle_plan.py

    # Specify projects explicitly
    python continuous_loop/populate_cycle_plan.py --projects PROJ-120,PROJ-121,PROJ-122

    # Specify approval log explicitly
    python continuous_loop/populate_cycle_plan.py --approval-log Reviews/results/2026-02-12_.../approval_log.md
"""

import argparse
import re
import sys
from datetime import datetime
from pathlib import Path

WORKSPACE = Path(__file__).parent.parent
ACTIVE_PROJECTS = WORKSPACE / "Projects" / "active_projects"
RESULTS_DIR = WORKSPACE / "Reviews" / "results"
CYCLE_PLAN = WORKSPACE / "continuous_loop" / "cycle_plan.md"


def find_latest_approval_log() -> Path | None:
    """Find the most recently modified approval_log.md in Reviews/results/."""
    logs = list(RESULTS_DIR.glob("*/prospective_projects/approval_log.md"))
    if not logs:
        return None
    return max(logs, key=lambda p: p.stat().st_mtime)


def parse_approval_log(log_path: Path) -> list[str]:
    """Extract PROJ-XX IDs from an approval_log.md file."""
    content = log_path.read_text(encoding="utf-8")
    return re.findall(r"(PROJ-\d+)", content)


def read_project_metadata(project_id: str) -> dict | None:
    """Read a project's plan.md and extract metadata."""
    plan_path = ACTIVE_PROJECTS / project_id / "plan.md"
    if not plan_path.exists():
        print(f"  [WARN] {project_id}: plan.md not found at {plan_path}")
        return None

    content = plan_path.read_text(encoding="utf-8")

    # Extract title from first heading: # PROJ-XX: Title
    title_match = re.search(r"^#\s+PROJ-\d+:\s*(.+)$", content, re.MULTILINE)
    title = title_match.group(1).strip() if title_match else project_id

    # Count phases from Quick Status table rows (lines with "Phase" and "|")
    phase_rows = re.findall(
        r"^\|\s*\d+\.\s+.+\|.+\|.+\|$", content, re.MULTILINE
    )
    phase_count = len(phase_rows)
    if phase_count == 0:
        # Fallback: count phase_N_checklist.md references
        phase_refs = re.findall(r"phase_(\d+)_checklist\.md", content)
        phase_count = len(set(phase_refs)) if phase_refs else 1

    # Check for dependencies
    deps_match = re.search(
        r"dependencies?[:\s]*(PROJ-\d+(?:\s*,\s*PROJ-\d+)*)",
        content,
        re.IGNORECASE,
    )
    dependencies = deps_match.group(1).strip() if deps_match else "None"

    return {
        "id": project_id,
        "title": title,
        "phases": phase_count,
        "dependencies": dependencies,
    }


def generate_cycle_plan(projects: list[dict]) -> str:
    """Generate cycle_plan.md content from project metadata."""
    now = datetime.now().strftime("%Y-%m-%d")
    lines = [
        "# Continuous Improvement Loop - Cycle Plan",
        "",
        "> **AUTOMATED EXECUTION MODE**",
        "> This file is read by Claude CLI in an automated loop. "
        "Each instance executes work on ONE project, updates this file, "
        "and exits.",
        "",
        "---",
        "",
        "## Agent Context",
        "",
        f"**Last Session:** {now}",
        "**Last Completed:** Cycle plan generated",
        "**Current Status:** Ready for execution",
        f"**Current Project:** {projects[0]['id']}" if projects else "**Current Project:** None",
        "**Current Phase:** Phase 1",
        "**Test Status:** Pending first run",
        "**Active Blockers:** None",
        "",
        "**Handoff Notes:**",
        f"- {len(projects)} projects queued for execution",
        "- Generated by continuous_loop/populate_cycle_plan.py",
        "- Begin with first incomplete project below",
        "",
        "---",
        "",
        "## Master Task List",
        "",
        "> **Note:** Each checkbox represents an entire project. "
        "Phase details are in the project's plan.md file.",
        "",
    ]

    for proj in projects:
        proj_id = proj["id"]
        title = proj["title"]
        phases = proj["phases"]
        deps = proj["dependencies"]
        plan_rel = f"Projects/active_projects/{proj_id}/plan.md"

        lines.extend([
            f"- [ ] **{proj_id}: {title}**",
            f"  - **Phases:** {phases} | **Status:** Ready | **Priority:** Medium",
            f"  - **Plan:** [{plan_rel}]({plan_rel})",
            "  - **Audit:** Not Started | **Cycles:** 0/5",
            f"  - **Dependencies:** {deps}",
            "",
            "---",
            "",
        ])

    lines.extend([
        "## Execution Log",
        "",
        "| Timestamp | Project | Action | Status | Tests | Commit | Notes |",
        "|-----------|---------|--------|--------|-------|--------|-------|",
        "",
        "---",
        "",
        "## Instructions for Automated Agent",
        "",
        "### Workflow Overview",
        "",
        "1. **Read this file first** - Understand current state from Agent Context",
        "2. **Find next incomplete project** - First `[ ]` in Master Task List",
        "3. **Load project plan:** `Projects/active_projects/PROJ-XX/plan.md`",
        "4. **Execute work loop:**",
        "   - Find next incomplete phase in project plan",
        "   - Load phase checklist: `Projects/active_projects/PROJ-XX/phase_N_checklist.md`",
        "   - Execute phase following strict TDD",
        "   - Update project plan and phase checklist",
        "   - Run tests - all must pass",
        "   - Git commit with format: `[PROJ-XX] Phase N: <description> - Automated`",
        "5. **Check project completion:**",
        "   - If phases remain -> Update Agent Context and exit",
        "   - If all phases complete -> Trigger audit (see below)",
        "6. **Audit workflow** (automatic when all phases complete):",
        "   - Run Protocol 04 (Audit Project)",
        "   - If audit passes -> Mark project `[x]` complete, move to next project",
        "   - If audit fails -> Add fix phases to project plan, continue with fixes",
        "   - Maximum 5 audit cycles per project",
        "   - After 5 failed cycles -> Mark project with issues, move to next project",
        "7. **Exit** after each phase or audit cycle",
        "",
        "### Detailed Instructions",
        "",
        "**Phase Execution:**",
        "- Follow Protocol 03a (Continue Working)",
        "- Use strict TDD: tests before implementation",
        "- Run `pytest tests/ --testmon` for incremental testing",
        "- Update phase checklist as you work",
        "- Add implementation notes",
        "- Commit after phase completion",
        "",
        "**Audit Trigger:**",
        "- Automatically triggered when all project phases complete",
        "- Follow Protocol 04 (Audit Project)",
        "- Use Protocol 08 (Automated Loop) for integration",
        "- Commit before each audit cycle",
        "- Update audit status in this file",
        "",
        "**Context Handoff:**",
        "- Update Agent Context section before exiting",
        "- Include current project, phase, and audit status",
        "- Note any blockers or decisions needed",
        "- Provide clear next steps",
        "",
        "---",
        "",
        "## Notes",
        "",
        "- Each project must complete all phases before moving to next project",
        "- Audit runs automatically after all phases complete",
        "- Maximum 5 audit cycles per project before moving on",
        "- Projects with failed audits are marked but not blocking",
        "- Follow all protocols in `Projects/protocols/`",
        "- Prioritize long-term maintainability over short-term convenience",
        "- Minimize technical debt in all decisions",
        "",
    ])

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Build cycle_plan.md from newly-created projects"
    )
    parser.add_argument(
        "--projects",
        help="Comma-separated PROJ-XX IDs (e.g., PROJ-120,PROJ-121)",
    )
    parser.add_argument(
        "--approval-log",
        help="Path to a specific approval_log.md file",
    )
    parser.add_argument(
        "--output",
        default=str(CYCLE_PLAN),
        help=f"Output file path (default: {CYCLE_PLAN})",
    )
    args = parser.parse_args()

    # Determine project list
    if args.projects:
        project_ids = [p.strip() for p in args.projects.split(",")]
        print(f"Using explicit project list: {project_ids}")
    elif args.approval_log:
        log_path = Path(args.approval_log)
        if not log_path.exists():
            print(f"ERROR: Approval log not found: {log_path}")
            sys.exit(1)
        project_ids = parse_approval_log(log_path)
        print(f"Found {len(project_ids)} projects in {log_path}")
    else:
        log_path = find_latest_approval_log()
        if not log_path:
            print("ERROR: No approval_log.md found in Reviews/results/")
            sys.exit(1)
        project_ids = parse_approval_log(log_path)
        print(f"Found {len(project_ids)} projects in {log_path}")

    # Deduplicate while preserving order
    seen = set()
    unique_ids = []
    for pid in project_ids:
        if pid not in seen:
            seen.add(pid)
            unique_ids.append(pid)
    project_ids = unique_ids

    if not project_ids:
        print("ERROR: No project IDs found")
        sys.exit(1)

    # Read metadata for each project
    projects = []
    for pid in project_ids:
        meta = read_project_metadata(pid)
        if meta:
            projects.append(meta)
            print(f"  {pid}: {meta['title']} ({meta['phases']} phases)")
        else:
            print(f"  {pid}: SKIPPED (plan.md not found)")

    if not projects:
        print("ERROR: No valid projects found")
        sys.exit(1)

    # Generate and write cycle_plan.md
    content = generate_cycle_plan(projects)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    print(f"\nGenerated {output_path}")
    print(f"  Projects: {len(projects)}")
    print(f"  Total phases: {sum(p['phases'] for p in projects)}")


if __name__ == "__main__":
    main()
