# -*- coding: utf-8 -*-
"""Tests for global fleet ID generation on Galaxy.

Part 1 of fleet ID collision fix: fleet IDs must be globally unique
across all empires, generated by Galaxy (not per-empire counters).
"""
import pytest

from game.core.hex_math import HexCoord
from game.strategy.data.galaxy import Galaxy
from game.strategy.data.empire import Empire
from game.strategy.data.fleet import Fleet


class TestGalaxyFleetIdGeneration:
    """Galaxy should own the fleet ID counter, producing globally unique IDs."""

    def test_galaxy_generates_sequential_fleet_ids(self):
        """Galaxy.get_next_fleet_id() returns incrementing IDs."""
        galaxy = Galaxy(radius=10)
        id1 = galaxy.get_next_fleet_id()
        id2 = galaxy.get_next_fleet_id()
        id3 = galaxy.get_next_fleet_id()
        assert id1 < id2 < id3

    def test_galaxy_fleet_ids_start_at_1(self):
        """First fleet ID from a fresh galaxy should be 1."""
        galaxy = Galaxy(radius=10)
        assert galaxy.get_next_fleet_id() == 1

    def test_two_empires_get_distinct_fleet_ids(self):
        """Fleets created for different empires via Galaxy get unique IDs."""
        galaxy = Galaxy(radius=10)

        id_empire0 = galaxy.get_next_fleet_id()
        id_empire1 = galaxy.get_next_fleet_id()
        id_empire0b = galaxy.get_next_fleet_id()

        assert id_empire0 != id_empire1
        assert id_empire0 != id_empire0b
        assert id_empire1 != id_empire0b

    def test_galaxy_fleet_id_survives_serialization(self):
        """Galaxy._next_fleet_id should persist across to_dict/from_dict."""
        galaxy = Galaxy(radius=10)
        # Consume a few IDs
        galaxy.get_next_fleet_id()
        galaxy.get_next_fleet_id()
        galaxy.get_next_fleet_id()

        data = galaxy.to_dict()
        restored = Galaxy.from_dict(data)

        # Next ID should continue from where we left off
        assert restored.get_next_fleet_id() == galaxy.get_next_fleet_id() - 1 + 1
        # More precisely: both should return 4 (since original consumed 1,2,3)
        # Actually let's just check restored gives 4
        # We already called get_next_fleet_id on original (which returned 4),
        # so re-check by constructing fresh:
        galaxy2 = Galaxy(radius=10)
        for _ in range(3):
            galaxy2.get_next_fleet_id()
        data2 = galaxy2.to_dict()
        restored2 = Galaxy.from_dict(data2)
        assert restored2.get_next_fleet_id() == 4

    def test_galaxy_fleet_id_counter_in_serialized_data(self):
        """to_dict output should contain _next_fleet_id key."""
        galaxy = Galaxy(radius=10)
        galaxy.get_next_fleet_id()  # consume ID 1
        data = galaxy.to_dict()
        assert '_next_fleet_id' in data
        assert data['_next_fleet_id'] == 2  # next available

    def test_no_fleet_id_collision_in_registry(self):
        """Two fleets from different empires must not collide in the registry."""
        galaxy = Galaxy(radius=10)
        empire0 = Empire(0, "Player", (0, 0, 255))
        empire1 = Empire(1, "AI", (255, 0, 0))
        empire0.set_galaxy(galaxy)
        empire1.set_galaxy(galaxy)

        fleet0 = Fleet(galaxy.get_next_fleet_id(), 0, HexCoord(0, 0))
        fleet1 = Fleet(galaxy.get_next_fleet_id(), 1, HexCoord(5, 5))

        empire0.add_fleet(fleet0)
        empire1.add_fleet(fleet1)

        # Both fleets should be independently retrievable
        assert galaxy.get_fleet_by_id(fleet0.id) is fleet0
        assert galaxy.get_fleet_by_id(fleet1.id) is fleet1
        assert fleet0.id != fleet1.id


class TestEmpireNoLongerOwnsFleetId:
    """Empire should NOT have fleet ID generation after migration."""

    def test_empire_has_no_next_fleet_id(self):
        """Empire should not have _next_fleet_id or get_next_fleet_id."""
        empire = Empire(0, "Test", (0, 0, 0))
        assert not hasattr(empire, 'get_next_fleet_id'), \
            "Empire.get_next_fleet_id should be removed — Galaxy owns fleet IDs now"

    def test_empire_serialization_no_fleet_id_counter(self):
        """Empire.to_dict should not include _next_fleet_id."""
        empire = Empire(0, "Test", (0, 0, 0))
        data = empire.to_dict()
        assert '_next_fleet_id' not in data
